version: '3.8'

services:
  shopify-returns-agency:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - LOG_LEVEL=INFO
      - RETURN_WINDOW_DAYS=30
      # Add your Shopify webhook secret here or use .env file
      # - SHOPIFY_WEBHOOK_SECRET=your_webhook_secret_here
    env_file:
      - .env
    volumes:
      # Persist logs outside container
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - shopify-returns-agency
    restart: unless-stopped
    profiles:
      - production  # Only run with --profile production

networks:
  default:
    name: shopify-returns-network 